# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit sugarglider.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE, 
                      message = FALSE)


library(sugarglider)
library(knitr)
library(ggplot2)
library(sf)
library(tidyverse)
library(grid)
library(viridis)
library(gridExtra)
library(ozmaps)
library(ggthemes)
library(kableExtra)
library(usmap)
library(ggiraph)
library(leaflet)
library(tinytex)


## ----fig.cap="The diagram depicts the structure of a glyph-map. The initial layer represents the base map, which can be generated using ggplot2::geom_sf() and ggplot2::geom_polygon(). Subsequent layers comprise of glyph boxes and reference lines, which are generated through add_glyph_boxes() and add_ref_lines() respectively. The fourth layer encompasses the glyph itself, offering users the choice to depict ribbon glyphs (geom_glyph_ribbon()) or segment glyphs (geom_segment_glyph()). The legend layer is optional. It enabling users to display a legend—a magnified version of one of the glyphs—using add_glyph_legend()."----
include_graphics("figures/glyphmap-layers.png")


## ----eval = FALSE, echo=TRUE--------------------------------------------------
#> # Ribbon glyph
#> vic_temp |>
#>    ggplot(aes(x_major = long,
#>               y_major = lat,
#>               x_minor = month,
#>               ymin_minor = tmin,
#>               ymax_minor = tmax)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   geom_glyph_ribbon() +
#>   theme_glyph()
#> 
#> # Segment glyph
#> vic_temp |>
#>    ggplot(aes(x_major = long,
#>               y_major = lat,
#>               x_minor = month,
#>               y_minor = tmin,
#>               yend_minor = tmax)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   geom_glyph_segment() +
#>   theme_glyph()


## ----comparisonPlot, fig.cap = "A comparison between ribbon and segment glyph-maps: Glyph boxes and reference lines have been added to frame each glyph and introduce a line that divides each glyph midway, helping users make inferences about the plot. Additional coding is necessary to create the base map and adjust the width and height of each glyph."----

include_graphics("figures/ribbon_segment.png")


## ----echo = TRUE--------------------------------------------------------------
glimpse(aus_temp)


## ----eval=FALSE, echo=TRUE----------------------------------------------------
#> # Default rescale
#> nsw_temp |>
#>    ggplot(aes(x_major = long,
#>               y_major = lat,
#>               x_minor = month,
#>               ymin_minor = tmin,
#>               ymax_minor = tmax)) +
#>   geom_glyph_ribbon() +
#>   theme_glyph()
#> 
#> # Custom rescale
#> custom_rescale <- function(dx) {
#>   rng <- range(dx, na.rm = TRUE)
#>   # Rescale dx to [0,1]
#>   rescaled <- (dx - rng[1]) / (rng[2] - rng[1])
#> }
#> 
#> nsw_temp |>
#>    ggplot(aes(x_major = long,
#>               y_major = lat,
#>               x_minor = month,
#>               ymin_minor = tmin,
#>               ymax_minor = tmax)) +
#>   geom_glyph_ribbon(x_scale = custom_rescale,
#>                     y_scale = custom_rescale) +
#>   theme_glyph()


## ----defaultRescale, fig.cap="The figure illustrates the effect of rescaling on ribbon glyphs. With the default rescaling, all minor axes are adjusted to fit within the interval [-1, 1], whereas the custom rescale function adjusts the minor axes to the interval [0, 1]. Additional code is required to plot the base map alongside the rescaled glyphs."----

include_graphics("figures/custom_rescale.png")


## ----eval=FALSE, echo=TRUE----------------------------------------------------
#> # Global rescale
#> aus_temp |>
#>   ggplot(aes(
#>     x_major = long,
#>     y_major = lat,
#>     x_minor = month,
#>     y_minor = tmin,
#>     yend_minor = tmax)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   geom_glyph_segment(global_rescale = TRUE) +
#>   theme_glyph()
#> 
#> # Local Rescale
#> aus_temp |>
#>   ggplot(aes(
#>     x_major = long,
#>     y_major = lat,
#>     x_minor = month,
#>     y_minor = tmin,
#>     yend_minor = tmax)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   geom_glyph_segment(global_rescale = FALSE) +
#>   theme_glyph()


## ----fig.cap="The figure highlights the impact of global and local rescaling on segment glyphs. With global rescaling, the temperature range is uniform across all glyphs, allowing users to compare variation in temperature between stations across Australia. In contrast, with local rescaling, the temperature range varies between glyphs, enabling more detailed insights into the temperature distribution at individual stations. Additional code is required to plot the base map and specify the xlim for the sf coordinates."----

include_graphics("figures/global_rescale.png")



## ----echo=FALSE, fig.cap="Diagram highlights how spatial data (geographical location) is combined with temporal data (measurements over time) to create a spatio-temporal visualization. In sugarglider, the transformation maps each station's temporal measurements into a visual glyph, allowing users to see patterns over time across different spatial locations."----
knitr::include_graphics("figures/diagram-transformation.png")


## ----echo=TRUE, eval=FALSE----------------------------------------------------
#> aus_temp |>
#>   ggplot(aes(
#>     x_major = long,
#>     y_major = lat,
#>     x_minor = month,
#>     y_minor = tmin,
#>     yend_minor = tmax)) +
#>   add_glyph_boxes() +
#>   geom_point(aes(x = long, y = lat,
#>                  color = "Weather Station")) +
#>   geom_glyph_segment() +
#>   theme_glyph()


## ----fig.cap="Daily temperature variations across Australian weather stations are visualized using Geom points to display the weather station locations. Additional codes are required for the base map."----

include_graphics("figures/temp_var.png")


## ----echo=TRUE, eval=FALSE----------------------------------------------------
#> aus_temp |>
#>    group_by(id) |>
#>    mutate(prcp = mean(prcp, na.rm = TRUE)) |>
#>    ggplot(aes(x_major = long, y_major = lat,
#>               x_minor = month, ymin_minor = tmin,
#>               ymax_minor = tmax,
#>               fill = prcp, color = prcp)) +
#>    add_glyph_boxes() +
#>    add_ref_lines() +
#>    geom_glyph_ribbon() +
#>    theme_glyph()


## ----fig.cap="Precipitation and Temperature Ranges Across Australia. Each glyph is color coded based on the level of precipitation, with sky blue representing the lowest and navy blue representing the highest. Additional codes are needed for the base map and additional theme customization."----

include_graphics("figures/prcp_temp.png")


## ----echo=TRUE, eval=FALSE----------------------------------------------------
#> historical_temp |>
#>   filter(id %in% c("ASN00026021", "ASN00085291", "ASN00084143")) |>
#>    ggplot(aes(color = factor(year), fill = factor(year),
#>               group = interaction(year,id),
#>               x_major = long, y_major = lat,
#>               x_minor = month, ymin_minor = tmin,
#>               ymax_minor = tmax)) +
#>    add_glyph_boxes() +
#>    add_ref_lines() +
#>    geom_glyph_ribbon() +
#>    theme_glyph()


## ----fig.cap="Temperature Trends in Selected Victorian Weather Stations. Additional codes are required for the base map, title, and further theme customization."----

include_graphics("figures/hist_temp.png")


## ----echo=TRUE, eval=FALSE----------------------------------------------------
#> set.seed(28493)
#> aus_temp |>
#>    ggplot(aes(x_major = long, y_major = lat,
#>               x_minor = month, ymin_minor = tmin,
#>               ymax_minor = tmax)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   add_glyph_legend() +
#>   geom_glyph_ribbon() +
#>   theme_glyph()


## ----fig.cap="Temperature Ranges Across Australia with Glyph Legend. Additional code is needed for the base map and additional theme customization."----

include_graphics("figures/legend_glyph.png")


## -----------------------------------------------------------------------------
head(train) |>
  kable() |> kable_styling()


## ----echo=TRUE, eval=FALSE----------------------------------------------------
#> 
#> # Generate a list of unique train stations
#> df_station <- train$station_name |> unique()
#> 
#> # Generate PNG of all the ribbon glyph
#> purrr::map(1:length(df_station), function(i) {
#>   dt <- train |> filter(station_name == df_station[i])
#>   p <- dt |>
#>   ggplot(aes(x_major = long, y_major = lat,
#>                    x_minor = month_year, ymin_minor = min_monthly,
#>                    ymax_minor = max_monthly)) +
#>     add_glyph_boxes(color = "#FFAD60",
#>                     fill = "#FFEEAD", alpha = 0.5,
#>                     linewidth = 1, width = 3, height  =2) +
#>     add_ref_lines(color = "#FFAD60", alpha = 1,
#>                   linewidth = 1, width = 3, height  =2) +
#>     geom_glyph_ribbon(color = "#A66E38", fill = "#A66E38",
#>                       width = 3, height  =2) +
#>     theme_void()
#> 
#>   file_path <- paste0("figures/glyph_", df_station[i], ".png")
#>   ggsave(file_path, plot = p, width = 3, height = 2, units = "in", dpi = 300,
#>          bg = "transparent")
#>   return(file_path)
#> 
#>   }) -> train_png
#> 


## ----echo=TRUE, eval=FALSE----------------------------------------------------
#> # Create a leaflet map
#> leaflet_map <- leaflet() |>
#>   addProviderTiles("CartoDB.Positron") |>
#>   addScaleBar(position = "bottomleft")


## ----echo=TRUE,eval=FALSE-----------------------------------------------------
#> # Loop through the PNG files and add them to the map
#> for (i in seq_along(train_png)) {
#>   icon <- makeIcon(iconUrl = train_png[i], iconWidth = 100, iconHeight = 60)
#> 
#>   dt <- train |> filter(station_name == df_station[i])
#>   leaflet_map <- leaflet_map |>
#>     addMarkers(lng = dt$long[1], lat = dt$lat[1], icon = icon,
#>                label = dt$station_name, options = markerOptions(opacity = 0.1))
#> }
#> 
#> leaflet_map


## ----fig.cap="Screenshot of the hourly train station traffic in Melbourne. Each glyph represent hourly traffic, with peaks occurring during typical commuting hours (morning and evening rush hours)"----
include_graphics("figures/leaflet.jpg")


## ----eval=FALSE, echo=TRUE----------------------------------------------------
#> weekday <- station |>
#>   group_by(station_name) |>
#>   ggplot(aes(x_major = long, y_major = lat,
#>              x_minor = hour, y_minor = min_weekday,
#>              yend_minor = max_weekday,
#>              color = services, fill = services)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   geom_glyph_segment(global_rescale = FALSE) +
#>   theme_glyph() +
#>   labs(title = "Weekday Patronage") +
#>   theme_glyph()
#> 
#> 
#> weekend <- station |>
#>   group_by(station_name) |>
#>   ggplot(aes(x_major = long, y_major = lat,
#>              x_minor = hour, y_minor = min_weekend,
#>              yend_minor = max_weekend,
#>              fill = services, color = services)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   geom_glyph_segment(global_rescale = FALSE) +
#>   theme_glyph() +
#>   labs(title = "Weekday Patronage") +
#>   theme_glyph()


## ----fig.cap="Patronage at various train stations in Melbourne City LGA on weekdays versus weekends. Each glyph is color-coded by the number of train services at each station. Additional code is required to construct the base map and customize the plot further."----
include_graphics("figures/weekend_weekday.png")


## -----------------------------------------------------------------------------
head(flights) |>
  kable() |> kable_styling()


## ----echo=TRUE, eval=FALSE----------------------------------------------------
#> # Specify tooltip for ggiraph
#> flights <- flights |>
#>   mutate(tooltip = paste("origin: ",origin,
#>                          "\nmonth: ", month,
#>                          "\nmin_flights: ", min_flights,
#>                          "\nmax_flights: ", max_flights))
#> 
#> fl <- flights |>
#>   ggplot(aes(x_major = long, y_major = lat,
#>              x_minor = month, y_minor = min_flights,
#>              yend_minor = max_flights,
#>              tooltip = tooltip)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   geom_glyph_segment() +
#>   theme_glyph()
#> 
#> # Interactive plot using ggiraph
#> girafe(ggobj = fl)


## ----fig.cap="Monthly Flight Variability Based on the top 10 US airports with high cancellation rates. Additional codes are needed for the base map and additional theme customization."----
include_graphics("figures/monthly-flight-variability.png")


## ----echo=TRUE, eval=FALSE----------------------------------------------------
#> # South Region
#> flights |>
#>   filter(origin %in% c("ATL", "CLT", "MCO", "DFW")) |>
#>   ggplot(aes(x_major = long, y_major = lat,
#>              x_minor = month, ymin_minor = min_flights,
#>              ymax_minor = max_flights)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   geom_glyph_ribbon() +
#>   theme_glyph()
#> 
#> # West region
#> flights |>
#>   filter(origin %in% c("PHX", "LAS", "LAX", "SEA")) |>
#>   ggplot(aes(x_major = long, y_major = lat,
#>              x_minor = month, ymin_minor = min_flights,
#>              ymax_minor = max_flights)) +
#>   add_glyph_boxes() +
#>   add_ref_lines() +
#>   geom_glyph_ribbon() +
#>   theme_glyph()


## ----fig.cap="Comparison of flight patterns between the western and southern regions. Additional codes are needed for the base map and additional theme customization."----

include_graphics("figures/west_south.png")

